### ISSUE TITLE
Error: Unknown transform 'collections'

### ISSUE THREAD

**Issue by belusky** [uiv-lib/uiv#296]
Today I cloned repositary and run into issue with build.

### Steps to reproduce the problem
```
$ npm run dist:esm
```

### Actual behavior
Build failed with error

```
> uiv@0.32.2 dist:esm D:\Programing\xampp\htdocs\workspace\uiv
> rollup -c build/rollup.conf.js

D:\Programing\xampp\htdocs\workspace\uiv\src\index.js → dist\uiv.common.js, dist\uiv.esm.js...
[!] (vue plugin) Error: Unknown transform 'collections'
src\components\carousel\Carousel.vue
Error: Unknown transform 'collections'
    at error (D:\Programing\xampp\htdocs\workspace\uiv\node_modules\rollup\dist\rollup.js:189:14)
    at Promise.resolve.then.catch.err (D:\Programing\xampp\htdocs\workspace\uiv\node_modules\rollup\dist\rollup.js:17593:6)
    at <anonymous>
```

I cloned it before 6 months ago (version 0.27.0) and build step worked.
Tried node version 8 and 9.

**Comment by belusky** [comment]
Any suggestion from anyone?

**Comment by wxsms** [comment]
my node & rollup versions, which runs fine. hope it helps.

node@8.12.9
rollup@0.52.1
rollup-plugin-vue@3.0.0
rollup-plugin-babel@3.0.2
rollup-plugin-node-resolve@3.0.0

**Comment by wxsms** [comment]
should be fix in v1
