### ISSUE TITLE
[MultiSelect] dropdown-menu always open

### ISSUE THREAD

**Issue by zhangsenhua** [uiv-lib/uiv#313]
I use MultiSelect. After selecting one option, click another query button (after selecting this option, you don't need to click other parts of the page, please click the query button directly), the "Disable" of MultiSelect will be set to true. The dropdown-menu cannot be closed, always open, even if I click elsewhere on the page

**Comment by wxsms** [comment]
Could you pls add a minimal reproduction for this issue? I don't understand your explaination.

**Comment by wxsms** [comment]
closing due to no response.
