### ISSUE TITLE
MultiSelect Improvements

### ISSUE THREAD

**Issue by kadirkahraman** [uiv-lib/uiv#324]
I'm using multi-select component in my personal project. I need to some improvements. I'm listing below.

<details>
<summary>Custom Options</summary>

I want to add customized options. For example I need to add avatar for every options. 

Example screenshot is below
![Screen Shot 2020-06-15 at 11 42 40](https://user-images.githubusercontent.com/44665266/84638506-c5675b00-aeff-11ea-8a73-11565aa36b42.png)

</details>

<details>
<summary>Tooltip For Options</summary>

I need to add tooltips for every option. For example: 

* my value is `id`
* my label is `username`
* And I want to show user's fullname in the tooltip. 

Example screenshot is below
![Screen Shot 2020-06-15 at 12 07 46](https://user-images.githubusercontent.com/44665266/84639513-280d2680-af01-11ea-9abb-0a77f62553df.png)

</details>

<details>
<summary>Publish Search Event</summary>

I have some users' mail list. I have added as options for multi-select components. But I want to accept external mail addresses. 

Example screenshot is below
![Screen Shot 2020-06-15 at 11 42 40](https://user-images.githubusercontent.com/44665266/84640076-dfa23880-af01-11ea-98e7-e6d51819b7e6.png)
![Screen Shot 2020-06-15 at 11 42 54](https://user-images.githubusercontent.com/44665266/84640094-e335bf80-af01-11ea-89aa-5e4ba2da03c3.png)
![Screen Shot 2020-06-15 at 11 43 02](https://user-images.githubusercontent.com/44665266/84640117-ecbf2780-af01-11ea-8203-61e85ac4af62.png)

(asd@asd.asd mail address is comes from outside of the list) 
</details>

I developed something for the solution.

* I have added `fireEvent` prop for publishing search event. (Default is false. Because prevent unnecessary event publishing)

* I have added `tooltipEnabled` (default is false) and `tooltipKey` props for show tooltip actions.

* I have added `customOptionComponentKey` prop for using custom options. I am passing to option as a `item` prop

**Comment by wxsms** [comment]
Hi @kadirkahraman , the resuested feature is reasonable, by I think that it could be implemented by a more common way, something like:

**Comment by wxsms** [comment]
Hi @kadirkahraman  , the resuested feature is reasonable, by I think that it could be implemented by a more common way, something like:

1. custom options could be implemented by a `scoped slot`, which will meet both of your requirements better: tooltips or avatars, and all others.
2. Search event could be emit, but the same, to achive your requirement a slot is still better, which could be a more common solution.

If you'd like to change your code design, pls let me know. otherwise I can help with this, too. Thanks.

**Comment by kadirkahraman** [comment]
@wxsms thanks for your feedback. I'll change my code in a short time 👍

**Comment by wxsms** [comment]
@kadirkahraman Hi, this lib has been migrated, please pull upstream code and create a new PR to target `dev` branch if you still want this feature.

**Comment by kadirkahraman** [comment]
@wxsms Hi, I've created new PR for these improvements. #343  fyi

**Comment by wxsms** [comment]
@kadirkahraman pls see my comment in pr.

**Comment by kadirkahraman** [comment]
thanks I'm looking 👍

**Comment by kadirkahraman** [comment]
@wxsms hi. Thanks for your comments. I've completed them. You can review whenever you want. I don't have any experience on vue testing. Can you please help me about tests?

**Comment by wxsms** [comment]
merged. I will help complete testing before release. thanks.
